### PR TITLE
AB#80959_fix_timezone_for_export

### PR DESCRIPTION
**Pull request by MwanPygmay**
# Description

Included timezone in export function to get the correct time. This modifies the format from YYYY-MM-DD to MM/DD/YYYY but this is coherent with front grid display.

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/80959)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested for datetime and date.

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-backend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by MwanPygmay** [comment]
Made required changes for time and datetime questions.
For the history, the format and timezone are indeed messed up in the export, but so are they in the UI, so maybe not the scope of this ticket?
Screenshot 2023-12-07 at 10 10 53

**Comment by AntoineRelief** [comment]
> Made required changes for time and datetime questions. For the history, the format and timezone are indeed messed up in the export, but so are they in the UI, so maybe not the scope of this ticket? Screenshot 2023-12-07 at 10 10 53

@MwanPygmay 
I think the values are coming from the back

**Comment by AntoineRelief** [comment]
> > Made required changes for time and datetime questions. For the history, the format and timezone are indeed messed up in the export, but so are they in the UI, so maybe not the scope of this ticket? Screenshot 2023-12-07 at 10 10 53
> 
> @MwanPygmay I think the values are coming from the back so the back is certainly responsible from this format

@MwanPygmay 
This is what I found in the recordHistory file in the back:

          case 'date':
            if (change.old !== undefined)
              change.old = new Date(change.old).toLocaleDateString();
            if (change.new !== undefined)
              change.new = new Date(change.new).toLocaleDateString();
            break;
          case 'datetime':
          case 'datetimelocal':
            if (change.old !== undefined)
              change.old = new Date(change.old).toLocaleString();
            if (change.new !== undefined)
              change.new = new Date(change.new).toLocaleString();
            break;
          case 'time':
            if (change.old !== undefined)
              change.old = new Date(change.old).toTimeString();
            if (change.new !== undefined)
              change.new = new Date(change.new).toTimeString();
            break;

**Comment by AntoineRelief** [comment]
@MwanPygmay @estelafs 
all good for this one 👍 

@RenzoPrats 
reverted in this one some of the changes made in the other branch for ref data

**Pull request merged**
